apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"creationTimestamp":"2018-02-02T18:54:49Z","labels":{"chart":"prometheus-0.1.4"},"name":"pk8s-prometheus-kube-state-metrics","namespace":"","resourceVersion":"831","selfLink":"/apis/rbac.authorization.k8s.io/v1/clusterroles/pk8s-prometheus-kube-state-metrics","uid":"8b578cd0-084a-11e8-a2ea-42010a8a0005"},"rules":[{"apiGroups":[""],"resources":["services","nodes","pods","resourcequotas"],"verbs":["list","watch"]},{"apiGroups":["extensions"],"resources":["daemonsets","deployments","replicasets"],"verbs":["list","watch"]}]}
  creationTimestamp: 2018-02-02T18:54:49Z
  labels:
    chart: prometheus-0.1.4
  name: pk8s-prometheus-kube-state-metrics
  resourceVersion: "291298"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/pk8s-prometheus-kube-state-metrics
  uid: 8b578cd0-084a-11e8-a2ea-42010a8a0005
rules:
- apiGroups:
  - ""
  resources:
  - services
  - limitranges
  - replicationcontrollers
  - nodes
  - pods
  - resourcequotas
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - list
  - watch
