apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recast-autoscale
spec:
  scaleTargetRef:
    kind: Deployment
    name: recast-deployment
  minReplicas: 1
  maxReplicas: 16
  targetCPUUtilizationPercentage: 10
