apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: recast-deployment
spec:
  selector:
    matchLabels:
      app: recast
      stage: prod
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recast
        stage: prod
    spec:
      containers:
      - name: recast
        image: kfengbest/mst-js-recast
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: VERSION
          value: RECAST_VERSION
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "300m"  

            
