apiVersion: v1
kind: Service
metadata:
  name: recast-service
spec:
  selector:
    app: recast
    stage: prod
  ports:
    - port: 80
      targetPort: http
  type: LoadBalancer
  externalTrafficPolicy: Local

