apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recast-autoscale
spec:
  scaleTargetRef:
    kind: Deployment
    name: my-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10 