apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: recast-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recast
      stage: prod
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recast
        stage: prod
    spec:
      containers:
      - name: recast
        image: kfengbest/mst-js-recast
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: VERSION
          value: v1.0.3

            
